import './globals.css'
import { Inter, Archivo } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const archivo = Archivo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-Archivo',
  weight: ["100", "200", "300", "400", "500", "600", "700"],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${archivo.variable}`}>{children}</body>
    </html>
  )
}
